// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "45b19a11-716c-42a7-9bbb-17c0b9c0c434";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onTemperaturaAmbienteChange();
void onUmidadeAmbienteChange();
void onUmidadeSoloChange();
void onControleManualBombaChange();
void onEstadoBombaChange();
void onModoManualChange();

float temperaturaAmbiente;
float umidadeAmbiente;
int umidadeSolo;
bool controleManualBomba;
bool estadoBomba;
bool modoManual;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(temperaturaAmbiente, READWRITE, ON_CHANGE, onTemperaturaAmbienteChange);
  ArduinoCloud.addProperty(umidadeAmbiente, READWRITE, ON_CHANGE, onUmidadeAmbienteChange);
  ArduinoCloud.addProperty(umidadeSolo, READWRITE, ON_CHANGE, onUmidadeSoloChange);
  ArduinoCloud.addProperty(controleManualBomba, READWRITE, ON_CHANGE, onControleManualBombaChange);
  ArduinoCloud.addProperty(estadoBomba, READWRITE, ON_CHANGE, onEstadoBombaChange);
  ArduinoCloud.addProperty(modoManual, READWRITE, ON_CHANGE, onModoManualChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
